export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_CRITERIA_SUCCESS = 'LOAD_CRITERIA_SUCCESS';
export const LOAD_INSPECTION_SUCCESS = 'LOAD_INSPECTION_SUCCESS';
export const CREATE_INSPECTION_SUCCESS = 'CREATE_INSPECTION_SUCCESS';
export const UPDATE_INSPECTION_SUCCESS = 'UPDATE_INSPECTION_SUCCESS';
export const SAVE_INSPECTION_RESULT_SUCCESS = 'SAVE_INSPECTION_RESULT_SUCCESS';
